// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPWdGYiaNt1tvxOYiBik8GGDmVMdmyIY',
    appId: '1:331660912325:web:837336748b9a2a1ccf32ac',
    messagingSenderId: '331660912325',
    projectId: 'firestore-758f8',
    authDomain: 'firestore-758f8.firebaseapp.com',
    storageBucket: 'firestore-758f8.appspot.com',
    measurementId: 'G-7QHGBMD7XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyC3EdG_Ba34VefaX4zCXEXyU4WD-oMeo',
    appId: '1:331660912325:android:12165bce2d5ed1adcf32ac',
    messagingSenderId: '331660912325',
    projectId: 'firestore-758f8',
    storageBucket: 'firestore-758f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHKeSdsx6WyrCqtt00a5SmpVkLVOcYci0',
    appId: '1:331660912325:ios:9357fb54d4c658cccf32ac',
    messagingSenderId: '331660912325',
    projectId: 'firestore-758f8',
    storageBucket: 'firestore-758f8.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHKeSdsx6WyrCqtt00a5SmpVkLVOcYci0',
    appId: '1:331660912325:ios:9357fb54d4c658cccf32ac',
    messagingSenderId: '331660912325',
    projectId: 'firestore-758f8',
    storageBucket: 'firestore-758f8.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFPWdGYiaNt1tvxOYiBik8GGDmVMdmyIY',
    appId: '1:331660912325:web:9297059cc86a2623cf32ac',
    messagingSenderId: '331660912325',
    projectId: 'firestore-758f8',
    authDomain: 'firestore-758f8.firebaseapp.com',
    storageBucket: 'firestore-758f8.appspot.com',
    measurementId: 'G-9TGB40R2JH',
  );
}
